### ISSUE TITLE
Early progression broken

### ISSUE THREAD

**Issue by myutin** [asylumdevgroup/Untitled-GT-Pack-2#4]
- Quest description of silkworms is very misleading (they passively produce cocoons, rather than occasionally dropping them on death)
- Granite, diorite, and andesite don't generate, so the only way to obtain them is by firing a Lot of gravel
- There's no recipe for Pyrotech's crushed limestone
- There's no recipe for the empty wooden form
- - The quest for unfired refractory bricks is also broken, requiring a deleted item
- There's no recipe for scraped hides
- Not necessarily a bug but water sources don't regenerate, so recipes that use water are more cumbersome than intended
- The iron/gold quests depend on finding a magnetite vein specifically, despite there being other sources of iron or gold ore
- - Consider changing the magnetite quest to a checkbox or to a side-quest

**Comment by mcadventurecity** [comment]
Thank you for reporting, I have looked into and fixed most of these issues in my local instance, however, there are a few I still need to test. Also, water being finite is partially intentional, but Oceans should be infinite (at least in my fixed instance).

**Comment by myutin** [comment]
Would you consider making water infinite in Rivers too? (if that's a
possibility)
In the early game, you likely mine gravel from riverbanks, which leaves
awkward patches of flowing water.

**Comment by mcadventurecity** [comment]
That can be done. I'll also try to get these fixes fully done sometime in the next week.
